services:
  - type: web
    name: web-saude-api
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: SWAGGER_ENABLED
        value: 'true'
      - key: THROTTLE_TTL_MS
        value: '60000'
      - key: THROTTLE_LIMIT
        value: '100'
      - key: CORS_ORIGINS
        value: http://localhost:5173,http://localhost:3000,http://localhost:4200
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES
        value: 15m
      - key: JWT_REFRESH_EXPIRES
        value: 7d
