export const AuditAction = {
  UNIT_APPROVED: 'UNIT_APPROVED',
  UNIT_REJECTED: 'UNIT_REJECTED',
  USER_ACTIVATED: 'USER_ACTIVATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  SPECIALTY_CREATED: 'SPECIALTY_CREATED',
  SPECIALTY_UPDATED: 'SPECIALTY_UPDATED',
  SPECIALTY_DELETED: 'SPECIALTY_DELETED',
} as const;

export type AuditActionName = (typeof AuditAction)[keyof typeof AuditAction];
